"""Compatibility facade for domain-organized Pydantic schemas."""
from schema_domains.bookmarks import BookmarkBackupInfo, BookmarkBulkAction, BookmarkBulkResult, BookmarkCreate, BookmarkFolderCreate, BookmarkFolderInfo, BookmarkFolderUpdate, BookmarkImportJobInfo, BookmarkInfo, BookmarkRestoreRequest, BookmarkUpdate, PublicBookmarkFolder, PublicBookmarkInfo, PublicCollectionResponse, SearchEngineCreate, SearchEngineInfo, SearchEngineUpdate, validate_http_url
from schema_domains.sync import SyncDashboardResponse, SyncDeviceSecretResponse, SyncDeviceSummary, SyncEventSummary, SyncFileSummary
from schema_domains.admin import AdminAuditEvidence, AdminOverviewBooks, AdminOverviewFiles, AdminOverviewHealth, AdminOverviewResponse, AdminOverviewRooms, AdminOverviewSync, AdminOverviewUsers, AdminSecurityCapabilities, AdminSecurityConfiguration, AdminSecurityCounts, AdminSecurityResponse, AgentConsoleStatus, RealtimeAuditEvidence
from schema_domains.live import LiveAdminSettingsUpdate, LiveAllowedUsersUpdate, LiveHeartbeatResponse, LiveInviteCreateRequest, LiveMessageCreateRequest, LiveRecordingCompleteRequest, LiveRecordingUpdateRequest, LiveSessionCreateRequest, LiveStatusResponse, LiveViewerSessionResponse, MediaMtxAuthRequest
from schema_domains.content import Photo, PhotoBase, PhotoCreate, PhotoUpdate, Post, PostBase, PostCreate, PostUpdate, PostWithAuthor, Tag, TagBase, TagCreate
from schema_domains.identity import RefreshTokenRequest, Token, TokenData, User, UserBase, UserCreate, UserPasswordUpdate, UserSimple, UserUpdate, UserUsernameUpdate
from schema_domains.links import LinkCategory, LinkCategoryBase, LinkCategoryCreate, LinkCategoryUpdate, WebsiteLink, WebsiteLinkBase, WebsiteLinkCreate, WebsiteLinkUpdate
from schema_domains.homepage import HomepageCardConfig, HomepageConfig, HomepagePublicResponse, HomepageSceneConfig, HomepageSettingsUpdate, HomepageSettingsView, _default_homepage_scenes
from schema_domains.rooms import KickMemberRequest, MusicRoomEventInfo, RoomCoreSnapshotPayload, RoomSnapshotPayload, SyncRoom, SyncRoomBase, SyncRoomCreate, SyncRoomInfo, SyncRoomLockUpdate, SyncRoomMemberInfo, SyncRoomMessage, SyncRoomMessageCreate, SyncRoomUpdate, TransferHostRequest, VideoPlaylistItemInfo, VideoSessionInfo, VideoSubtitleInfo, WSChatMessage, WSMemberUpdate, WSPlaybackControl
from schema_domains.requests import ResourceRequest, ResourceRequestBase, ResourceRequestCreate, ResourceRequestUpdate, WishlistReply, WishlistReplyBase, WishlistReplyCreate
from schema_domains.community import MessageBoardBase, MessageBoardCreate, MessageBoardResponse
from schema_domains.validation import _clean_optional_text, _validate_book_cover, _validate_book_tags, _validate_public_https_url, BOOK_READING_STATUSES, MEDIA_STATUSES, MEDIA_METADATA_FIELDS
from schema_domains.media import MediaCreate, MediaEntryAdminView, MediaEntryView, MediaMutationResult, MediaPatch, MediaRecentResponse
from schema_domains.books import BookAdminView, BookCatalogAdminResponse, BookCatalogPublicResponse, BookCreate, BookListAdminView, BookListCreate, BookListItemsUpdate, BookListPublicView, BookListUpdate, BookPublicView, BookUpdate

# Resolve the same forward references as the former monolithic module.
PostWithAuthor.model_rebuild(_types_namespace=globals())
MessageBoardResponse.model_rebuild(_types_namespace=globals())
HomepagePublicResponse.model_rebuild(_types_namespace=globals())
SyncRoomInfo.model_rebuild(_types_namespace=globals())

__all__ = ['AdminAuditEvidence', 'AdminOverviewBooks', 'AdminOverviewFiles', 'AdminOverviewHealth', 'AdminOverviewResponse', 'AdminOverviewRooms', 'AdminOverviewSync', 'AdminOverviewUsers', 'AdminSecurityCapabilities', 'AdminSecurityConfiguration', 'AdminSecurityCounts', 'AdminSecurityResponse', 'AgentConsoleStatus', 'BOOK_READING_STATUSES', 'BookAdminView', 'BookCatalogAdminResponse', 'BookCatalogPublicResponse', 'BookCreate', 'BookListAdminView', 'BookListCreate', 'BookListItemsUpdate', 'BookListPublicView', 'BookListUpdate', 'BookPublicView', 'BookUpdate', 'BookmarkBackupInfo', 'BookmarkBulkAction', 'BookmarkBulkResult', 'BookmarkCreate', 'BookmarkFolderCreate', 'BookmarkFolderInfo', 'BookmarkFolderUpdate', 'BookmarkImportJobInfo', 'BookmarkInfo', 'BookmarkRestoreRequest', 'BookmarkUpdate', 'HomepageCardConfig', 'HomepageConfig', 'HomepagePublicResponse', 'HomepageSceneConfig', 'HomepageSettingsUpdate', 'HomepageSettingsView', 'KickMemberRequest', 'LinkCategory', 'LinkCategoryBase', 'LinkCategoryCreate', 'LinkCategoryUpdate', 'LiveAdminSettingsUpdate', 'LiveAllowedUsersUpdate', 'LiveHeartbeatResponse', 'LiveInviteCreateRequest', 'LiveMessageCreateRequest', 'LiveRecordingCompleteRequest', 'LiveRecordingUpdateRequest', 'LiveSessionCreateRequest', 'LiveStatusResponse', 'LiveViewerSessionResponse', 'MEDIA_METADATA_FIELDS', 'MEDIA_STATUSES', 'MediaCreate', 'MediaEntryAdminView', 'MediaEntryView', 'MediaMtxAuthRequest', 'MediaMutationResult', 'MediaPatch', 'MediaRecentResponse', 'MessageBoardBase', 'MessageBoardCreate', 'MessageBoardResponse', 'MusicRoomEventInfo', 'Photo', 'PhotoBase', 'PhotoCreate', 'PhotoUpdate', 'Post', 'PostBase', 'PostCreate', 'PostUpdate', 'PostWithAuthor', 'PublicBookmarkFolder', 'PublicBookmarkInfo', 'PublicCollectionResponse', 'RealtimeAuditEvidence', 'RefreshTokenRequest', 'ResourceRequest', 'ResourceRequestBase', 'ResourceRequestCreate', 'ResourceRequestUpdate', 'RoomCoreSnapshotPayload', 'RoomSnapshotPayload', 'SearchEngineCreate', 'SearchEngineInfo', 'SearchEngineUpdate', 'SyncDashboardResponse', 'SyncDeviceSecretResponse', 'SyncDeviceSummary', 'SyncEventSummary', 'SyncFileSummary', 'SyncRoom', 'SyncRoomBase', 'SyncRoomCreate', 'SyncRoomInfo', 'SyncRoomLockUpdate', 'SyncRoomMemberInfo', 'SyncRoomMessage', 'SyncRoomMessageCreate', 'SyncRoomUpdate', 'Tag', 'TagBase', 'TagCreate', 'Token', 'TokenData', 'TransferHostRequest', 'User', 'UserBase', 'UserCreate', 'UserPasswordUpdate', 'UserSimple', 'UserUpdate', 'UserUsernameUpdate', 'VideoPlaylistItemInfo', 'VideoSessionInfo', 'VideoSubtitleInfo', 'WSChatMessage', 'WSMemberUpdate', 'WSPlaybackControl', 'WebsiteLink', 'WebsiteLinkBase', 'WebsiteLinkCreate', 'WebsiteLinkUpdate', 'WishlistReply', 'WishlistReplyBase', 'WishlistReplyCreate', '_clean_optional_text', '_default_homepage_scenes', '_validate_book_cover', '_validate_book_tags', '_validate_public_https_url', 'validate_http_url']
