"""legacy schema baseline

Revision ID: 0001_legacy_baseline
Revises:
Create Date: 2026-07-15 14:11:36.298220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_legacy_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_slug'), ['slug'], unique=True)

    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photos_id'), ['id'], unique=False)

    op.create_table('sync_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_token', sa.String(length=128), nullable=False),
    sa.Column('root_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('scan_requested', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_devices_device_token'), ['device_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_sync_devices_id'), ['id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('backup_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_jobs_id'), ['id'], unique=False)

    op.create_table('bookmark_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark_backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_backups_id'), ['id'], unique=False)

    op.create_table('bookmark_export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('export_type', sa.String(length=20), nullable=False),
    sa.Column('exported_count', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark_export_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_export_jobs_id'), ['id'], unique=False)

    op.create_table('bookmark_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['bookmark_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_folders_id'), ['id'], unique=False)

    op.create_table('bookmark_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark_import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_import_jobs_id'), ['id'], unique=False)

    op.create_table('bookmark_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_tags_id'), ['id'], unique=False)

    op.create_table('frp_operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frp_operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frp_operation_logs_id'), ['id'], unique=False)

    op.create_table('game_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=12), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('current_turn_user_id', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_turn_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_rooms_room_code'), ['room_code'], unique=True)

    op.create_table('link_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_categories_id'), ['id'], unique=False)

    op.create_table('message_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['message_board.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_board_id'), ['id'], unique=False)

    op.create_table('music_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_track_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_track_id', name='uq_music_favorite')
    )
    with op.batch_alter_table('music_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_favorites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_music_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('photo_tags',
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('pin_priority', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_slug'), ['slug'], unique=True)

    op.create_table('resource_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('reply_content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('external_link', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_requests_id'), ['id'], unique=False)

    op.create_table('sync_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('bytes_transferred', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sync_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_events_id'), ['id'], unique=False)

    op.create_table('sync_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('bytes_transferred', sa.Integer(), nullable=False),
    sa.Column('expected_size', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sync_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_files_relative_path'), ['relative_path'], unique=False)

    op.create_table('sync_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=20), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('host_user_id', sa.Integer(), nullable=False),
    sa.Column('control_mode', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('video_source', sa.Text(), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('video_size', sa.Integer(), nullable=True),
    sa.Column('video_hash', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=True),
    sa.Column('game_state', sa.Text(), nullable=True),
    sa.Column('current_time', sa.Float(), nullable=True),
    sa.Column('is_playing', sa.Boolean(), nullable=True),
    sa.Column('playback_version', sa.Integer(), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('auto_delete_file', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_rooms_room_code'), ['room_code'], unique=True)

    op.create_table('backup_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backup_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_files_id'), ['id'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('favicon', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_visited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['bookmark_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_id'), ['id'], unique=False)

    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_events_id'), ['id'], unique=False)

    op.create_table('game_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_invites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_invites_token'), ['token'], unique=True)

    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.id'], ),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_results_id'), ['id'], unique=False)

    op.create_table('game_room_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_room_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_room_members_id'), ['id'], unique=False)

    op.create_table('game_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_states_id'), ['id'], unique=False)

    op.create_table('message_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message_board.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_likes_id'), ['id'], unique=False)

    op.create_table('music_queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_track_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('stream_url', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['sync_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('music_queue_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_queue_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_music_queue_items_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_music_queue_items_status'), ['status'], unique=False)

    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_table('sync_room_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['sync_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_room_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_room_members_id'), ['id'], unique=False)

    op.create_table('sync_room_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['sync_rooms.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_room_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_room_messages_id'), ['id'], unique=False)

    op.create_table('website_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['link_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('website_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_links_id'), ['id'], unique=False)

    op.create_table('wishlist_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['resource_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_replies_id'), ['id'], unique=False)

    op.create_table('bookmark_tag_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmark_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['bookmark_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookmark_tag_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_tag_relations_id'), ['id'], unique=False)

    op.create_table('music_skip_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('queue_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['queue_item_id'], ['music_queue_items.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['sync_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_item_id', 'user_id', name='uq_music_skip_vote')
    )
    with op.batch_alter_table('music_skip_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_skip_votes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_music_skip_votes_room_id'), ['room_id'], unique=False)

    op.create_table('music_track_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('queue_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['queue_item_id'], ['music_queue_items.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['sync_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_item_id', 'user_id', name='uq_music_track_vote')
    )
    with op.batch_alter_table('music_track_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_track_votes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_music_track_votes_queue_item_id'), ['queue_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_music_track_votes_room_id'), ['room_id'], unique=False)

    op.create_table('restore_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['backup_file_id'], ['backup_files.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restore_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restore_jobs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restore_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restore_jobs_id'))

    op.drop_table('restore_jobs')
    with op.batch_alter_table('music_track_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_track_votes_room_id'))
        batch_op.drop_index(batch_op.f('ix_music_track_votes_queue_item_id'))
        batch_op.drop_index(batch_op.f('ix_music_track_votes_id'))

    op.drop_table('music_track_votes')
    with op.batch_alter_table('music_skip_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_skip_votes_room_id'))
        batch_op.drop_index(batch_op.f('ix_music_skip_votes_id'))

    op.drop_table('music_skip_votes')
    with op.batch_alter_table('bookmark_tag_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_tag_relations_id'))

    op.drop_table('bookmark_tag_relations')
    with op.batch_alter_table('wishlist_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_replies_id'))

    op.drop_table('wishlist_replies')
    with op.batch_alter_table('website_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_links_id'))

    op.drop_table('website_links')
    with op.batch_alter_table('sync_room_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_room_messages_id'))

    op.drop_table('sync_room_messages')
    with op.batch_alter_table('sync_room_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_room_members_id'))

    op.drop_table('sync_room_members')
    op.drop_table('post_tags')
    with op.batch_alter_table('music_queue_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_queue_items_status'))
        batch_op.drop_index(batch_op.f('ix_music_queue_items_room_id'))
        batch_op.drop_index(batch_op.f('ix_music_queue_items_id'))

    op.drop_table('music_queue_items')
    with op.batch_alter_table('message_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_likes_id'))

    op.drop_table('message_likes')
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_states_id'))

    op.drop_table('game_states')
    with op.batch_alter_table('game_room_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_room_members_id'))

    op.drop_table('game_room_members')
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_results_id'))

    op.drop_table('game_results')
    with op.batch_alter_table('game_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_invites_token'))
        batch_op.drop_index(batch_op.f('ix_game_invites_id'))

    op.drop_table('game_invites')
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_events_id'))

    op.drop_table('game_events')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_id'))

    op.drop_table('bookmarks')
    with op.batch_alter_table('backup_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_files_id'))

    op.drop_table('backup_files')
    with op.batch_alter_table('sync_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_rooms_room_code'))
        batch_op.drop_index(batch_op.f('ix_sync_rooms_id'))

    op.drop_table('sync_rooms')
    with op.batch_alter_table('sync_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_files_relative_path'))
        batch_op.drop_index(batch_op.f('ix_sync_files_id'))

    op.drop_table('sync_files')
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_events_id'))

    op.drop_table('sync_events')
    with op.batch_alter_table('resource_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_requests_id'))

    op.drop_table('resource_requests')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_posts_id'))

    op.drop_table('posts')
    op.drop_table('photo_tags')
    with op.batch_alter_table('music_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_music_favorites_id'))

    op.drop_table('music_favorites')
    with op.batch_alter_table('message_board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_board_id'))

    op.drop_table('message_board')
    with op.batch_alter_table('link_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_categories_id'))

    op.drop_table('link_categories')
    with op.batch_alter_table('game_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_rooms_room_code'))
        batch_op.drop_index(batch_op.f('ix_game_rooms_id'))

    op.drop_table('game_rooms')
    with op.batch_alter_table('frp_operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frp_operation_logs_id'))

    op.drop_table('frp_operation_logs')
    with op.batch_alter_table('bookmark_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_tags_id'))

    op.drop_table('bookmark_tags')
    with op.batch_alter_table('bookmark_import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_import_jobs_id'))

    op.drop_table('bookmark_import_jobs')
    with op.batch_alter_table('bookmark_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_folders_id'))

    op.drop_table('bookmark_folders')
    with op.batch_alter_table('bookmark_export_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_export_jobs_id'))

    op.drop_table('bookmark_export_jobs')
    with op.batch_alter_table('bookmark_backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_backups_id'))

    op.drop_table('bookmark_backups')
    with op.batch_alter_table('backup_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_jobs_id'))

    op.drop_table('backup_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    with op.batch_alter_table('sync_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_devices_id'))
        batch_op.drop_index(batch_op.f('ix_sync_devices_device_token'))

    op.drop_table('sync_devices')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photos_id'))

    op.drop_table('photos')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_slug'))
        batch_op.drop_index(batch_op.f('ix_games_id'))

    op.drop_table('games')
    # ### end Alembic commands ###
