"""phase1 security and restore reliability

Revision ID: 0002_phase1_security
Revises: 0001_legacy_baseline
Create Date: 2026-07-15 14:11:48.798273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '0002_phase1_security'
down_revision: Union[str, Sequence[str], None] = '0001_legacy_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

RESTORE_FK_NAME = "fk_restore_jobs_backup_file_id_backup_files"
NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}


def restore_backup_fk_name(bind) -> str:
    foreign_keys = sa.inspect(bind).get_foreign_keys("restore_jobs")
    for foreign_key in foreign_keys:
        if foreign_key.get("constrained_columns") == ["backup_file_id"]:
            return foreign_key.get("name") or RESTORE_FK_NAME
    raise RuntimeError("restore_jobs backup foreign key is missing")


def backfill_restore_metadata(bind) -> None:
    rows = bind.execute(
        sa.text(
            "SELECT restore_jobs.id, backup_files.file_path, backup_files.sha256 "
            "FROM restore_jobs LEFT JOIN backup_files "
            "ON backup_files.id = restore_jobs.backup_file_id"
        )
    ).mappings()
    for row in rows:
        raw_path = row["file_path"] or ""
        filename = raw_path.replace("\\", "/").rsplit("/", 1)[-1] or None
        bind.execute(
            sa.text(
                "UPDATE restore_jobs SET operation_id = :operation_id, "
                "source_filename = :source_filename, source_sha256 = :source_sha256, "
                "rollback_status = 'not_attempted' WHERE id = :restore_id"
            ),
            {
                "operation_id": str(uuid.uuid4()),
                "source_filename": filename,
                "source_sha256": row["sha256"],
                "restore_id": row["id"],
            },
        )


def backfill_post_slugs(bind) -> None:
    if bind.dialect.name in {"mysql", "mariadb"}:
        expression = "CONCAT('post-', id)"
    else:
        expression = "'post-' || id"
    bind.execute(
        sa.text(
            "UPDATE posts SET slug = " + expression +
            " WHERE slug IS NULL OR TRIM(slug) = ''"
        )
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_logs_outcome'), ['outcome'], unique=False)

    op.create_table('admin_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_files_stored_name'), ['stored_name'], unique=True)

    op.create_table('realtime_event_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('realtime_event_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_realtime_event_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_event_audit_logs_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_event_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_event_audit_logs_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_realtime_event_audit_logs_room_id'), ['room_id'], unique=False)

    with op.batch_alter_table('restore_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('source_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column(
            'rollback_status',
            sa.String(length=20),
            nullable=False,
            server_default='not_attempted',
        ))

    bind = op.get_bind()
    backfill_restore_metadata(bind)
    backfill_post_slugs(bind)
    existing_fk_name = restore_backup_fk_name(bind)

    with op.batch_alter_table(
        'restore_jobs',
        schema=None,
        naming_convention=NAMING_CONVENTION,
    ) as batch_op:
        batch_op.alter_column(
               'operation_id',
               existing_type=sa.String(length=36),
               nullable=False)
        batch_op.alter_column(
               'rollback_status',
               existing_type=sa.String(length=20),
               nullable=False,
               server_default=None)
        batch_op.alter_column('backup_file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_restore_jobs_operation_id'), ['operation_id'], unique=True)
        batch_op.drop_constraint(existing_fk_name, type_='foreignkey')
        batch_op.create_foreign_key(
            RESTORE_FK_NAME,
            'backup_files',
            ['backup_file_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    bind.execute(sa.text("DELETE FROM restore_jobs WHERE backup_file_id IS NULL"))
    existing_fk_name = restore_backup_fk_name(bind)
    with op.batch_alter_table(
        'restore_jobs',
        schema=None,
        naming_convention=NAMING_CONVENTION,
    ) as batch_op:
        batch_op.drop_constraint(existing_fk_name, type_='foreignkey')
        batch_op.create_foreign_key(
            RESTORE_FK_NAME,
            'backup_files',
            ['backup_file_id'],
            ['id'],
        )
        batch_op.drop_index(batch_op.f('ix_restore_jobs_operation_id'))
        batch_op.alter_column('backup_file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('rollback_status')
        batch_op.drop_column('source_sha256')
        batch_op.drop_column('source_filename')
        batch_op.drop_column('operation_id')

    with op.batch_alter_table('realtime_event_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_realtime_event_audit_logs_room_id'))
        batch_op.drop_index(batch_op.f('ix_realtime_event_audit_logs_outcome'))
        batch_op.drop_index(batch_op.f('ix_realtime_event_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_realtime_event_audit_logs_event_name'))
        batch_op.drop_index(batch_op.f('ix_realtime_event_audit_logs_actor_id'))

    op.drop_table('realtime_event_audit_logs')
    with op.batch_alter_table('admin_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_files_stored_name'))
        batch_op.drop_index(batch_op.f('ix_admin_files_id'))

    op.drop_table('admin_files')
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_outcome'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_logs_action'))

    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
