import { Download, FileDown, FolderSync, Link2, RefreshCw, Trash2, Upload } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'

import { API_ENDPOINTS } from '../config.js'
import apiClient from '../utils/request.js'

function formatSize(value) { const bytes = Number(value) || 0; if (bytes < 1024) return `${bytes} B`; const units = ['KB', 'MB', 'GB']; let size = bytes / 1024; let unit = units[0]; for (let i = 1; i < units.length && size >= 1024; i += 1) { size /= 1024; unit = units[i] } return `${size.toFixed(size >= 10 ? 1 : 2)} ${unit}` }

export default function AdminFilesPage() {
  const [sync, setSync] = useState({ status: 'loading', path: '', items: [] }); const [path, setPath] = useState(''); const [transfers, setTransfers] = useState([]); const [error, setError] = useState(''); const [transfer, setTransfer] = useState(null); const [uploading, setUploading] = useState(false)
  const detail = (reason, fallback) => { const value = reason?.response?.data?.detail; return typeof value === 'string' ? value : fallback }
  const loadSync = useCallback(async (nextPath = path) => { try { const [status, browse] = await Promise.all([apiClient.get(API_ENDPOINTS.ADMIN_FILE_SYNC_STATUS), apiClient.get(API_ENDPOINTS.ADMIN_FILE_SYNC_BROWSE, { params: { path: nextPath } })]); setSync({ status: status.data?.status || 'offline', path: browse.data?.path || nextPath, items: Array.isArray(browse.data?.items) ? browse.data.items : [] }) } catch (reason) { const message = detail(reason, '文件同步暂时不可用。'); setSync({ status: message.includes('离线') ? 'offline' : 'error', path: nextPath, items: [] }); setError(message) } }, [path])
  const loadTransfers = useCallback(async () => { try { const response = await apiClient.get(API_ENDPOINTS.ADMIN_TRANSFERS); setTransfers(Array.isArray(response.data) ? response.data : []) } catch (reason) { setError(detail(reason, '中转链接暂时无法载入。')) } }, [])
  useEffect(() => { loadSync(''); loadTransfers() }, [loadSync, loadTransfers])
  async function uploadTransfer(event) {
    const input = event.currentTarget; const file = input.files?.[0]; if (!file) return
    setUploading(true); setError('')
    try {
      let token = transfer?.token; let url = transfer?.url
      if (!token) { const response = await apiClient.post(API_ENDPOINTS.ADMIN_TRANSFERS); token = response.data?.token; if (!token) throw new Error('中转链接创建失败。'); url = `${window.location.origin}/transfer/${token}`; setTransfer({ token, url, ready: false }) }
      await apiClient.put(`/api/transfers/${token}`, file, { timeout: 0, params: { filename: file.name }, headers: { 'Content-Type': 'application/octet-stream' } })
      setTransfer({ token, url, ready: true }); await loadTransfers()
    } catch (reason) { if (reason.response?.status === 404) setTransfer(null); setError(detail(reason, '文件上传失败。')) } finally { setUploading(false); input.value = '' }
  }
  async function deleteTransfer(id) { if (!window.confirm('提前销毁这个中转链接？')) return; await apiClient.delete(API_ENDPOINTS.ADMIN_TRANSFER(id)); await loadTransfers() }
  async function downloadSync(item) { const itemPath = [sync.path, item.path].filter(Boolean).join('/'); const response = await apiClient.get(API_ENDPOINTS.ADMIN_FILE_SYNC_DOWNLOAD, { params: { path: itemPath }, responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = item.name; link.click(); URL.revokeObjectURL(url) }
  const goTo = (item) => { const next = [sync.path, item.path].filter(Boolean).join('/'); setPath(next); loadSync(next) }
  return <section className="admin-files-page"><header className="admin-page-heading"><div><p>管理控制台 / 文件</p><h2>文件</h2></div><button className="admin-icon-button" type="button" onClick={() => { loadSync(path); loadTransfers() }} aria-label="刷新文件"><RefreshCw size={16} /></button></header>{error && <p className="admin-inline-error" role="alert">{error}</p>}<div className="admin-file-cards"><article className="admin-file-card"><div className="admin-file-card__icon"><FolderSync size={21} /></div><p className="admin-file-card__label">READ ONLY / FRP</p><h3>文件同步</h3><p>实时浏览并下载 <code>/home/neet821/Public</code>，服务器不写回本机。</p><div className={`admin-file-status admin-file-status--${sync.status}`}>{sync.status === 'online' ? '在线' : sync.status === 'loading' ? '连接中' : sync.status === 'auth_failed' ? '鉴权失败' : '离线'}</div><div className="admin-file-browser"><div className="admin-file-browser__bar"><span>/{sync.path}</span>{sync.path && <button type="button" onClick={() => { const next = sync.path.split('/').slice(0, -1).join('/'); setPath(next); loadSync(next) }}>上一级</button>}</div>{sync.items.map((item) => <button className="admin-file-browser__item" type="button" key={item.path} onClick={() => item.path.endsWith('/') ? goTo(item) : downloadSync(item)}>{item.path.endsWith('/') ? <FolderSync size={15} /> : <FileDown size={15} />}<span>{item.name}</span>{!item.path.endsWith('/') && <Download size={14} />}</button>)}{sync.status === 'online' && !sync.items.length && <p className="admin-empty">目录为空。</p>}</div></article><article className="admin-file-card"><div className="admin-file-card__icon admin-file-card__icon--violet"><Link2 size={21} /></div><p className="admin-file-card__label">ANONYMOUS / 5 MIN IDLE</p><h3>文件中转</h3><p>在此页直接上传，成功后生成匿名上传下载链接，单个链接总量最多 2GB，五分钟无活动自动销毁。</p><label className="admin-transfer-upload"><Upload size={15} />{uploading ? '上传中…' : transfer?.ready ? '继续上传文件' : '选择文件上传'}<input aria-label="选择文件上传" type="file" onChange={uploadTransfer} disabled={uploading} /></label>{transfer?.ready && <div className="admin-transfer-created"><span>中转链接</span><input aria-label="中转链接" readOnly value={transfer.url} onFocus={(event) => event.target.select()} /></div>}<div className="admin-transfer-list">{transfers.map((item) => <div className="admin-transfer-row" key={item.id}><span><strong>{formatSize(item.total_bytes)} / {formatSize(item.max_bytes)}</strong><small>过期：{new Date(item.expires_at).toLocaleString('zh-CN')}</small></span><button type="button" onClick={() => deleteTransfer(item.id)} aria-label="销毁中转链接"><Trash2 size={15} /></button></div>)}</div></article></div></section>
}
