"""Stable legacy import surface for the domain SQLAlchemy models."""

from .accounts import User
from .admin import (
    AdminFile,
    TransferSession,
    TransferFile,
    AdminTransferNote,
    AdminAuditLog,
    HomepageSetting,
    RealtimeEventAuditLog,
)
from .live import (
    LiveSetting,
    LiveCredential,
    LiveAllowedUser,
    LiveInvite,
    LiveSession,
    LiveRecording,
    LiveViewerSession,
    LiveMessage,
)
from .sync import SyncDevice, SyncFile, SyncUpload, SyncEvent
from .catalog import Book, MediaEntry, BookList, BookListItem
from .content import post_tags, photo_tags, Post, Tag, Photo
from .links import LinkCategory, WebsiteLink
from .bookmarks import (
    BookmarkFolder,
    Bookmark,
    BookmarkTag,
    BookmarkTagRelation,
    BookmarkImportJob,
    SearchEngine,
    BookmarkExportJob,
    BookmarkBackup,
)
from .music import (
    CanonicalTrack,
    TrackProviderMapping,
    TrackAudioSource,
    TrackLyrics,
    MusicQueueItem,
    MusicRoomEvent,
    MusicSkipVote,
    MusicTrackVote,
    MusicFavorite,
    UserPlaylist,
    UserPlaylistItem,
)
from .rooms import (
    SyncRoom,
    VideoPlaylistItem,
    VideoSubtitle,
    VideoSession,
    SyncRoomMember,
    SyncRoomMessage,
)
from .community import MessageBoard, MessageLike, ResourceRequest, WishlistReply

from .base import Base

__all__ = [
    "User",
    "AdminFile",
    "TransferSession",
    "TransferFile",
    "AdminTransferNote",
    "AdminAuditLog",
    "HomepageSetting",
    "RealtimeEventAuditLog",
    "LiveSetting",
    "LiveCredential",
    "LiveAllowedUser",
    "LiveInvite",
    "LiveSession",
    "LiveRecording",
    "LiveViewerSession",
    "LiveMessage",
    "SyncDevice",
    "SyncFile",
    "SyncUpload",
    "SyncEvent",
    "Book",
    "MediaEntry",
    "BookList",
    "BookListItem",
    "post_tags",
    "photo_tags",
    "Post",
    "Tag",
    "Photo",
    "LinkCategory",
    "WebsiteLink",
    "BookmarkFolder",
    "Bookmark",
    "BookmarkTag",
    "BookmarkTagRelation",
    "BookmarkImportJob",
    "SearchEngine",
    "BookmarkExportJob",
    "BookmarkBackup",
    "CanonicalTrack",
    "TrackProviderMapping",
    "TrackAudioSource",
    "TrackLyrics",
    "MusicQueueItem",
    "MusicRoomEvent",
    "MusicSkipVote",
    "MusicTrackVote",
    "MusicFavorite",
    "UserPlaylist",
    "UserPlaylistItem",
    "SyncRoom",
    "VideoPlaylistItem",
    "VideoSubtitle",
    "VideoSession",
    "SyncRoomMember",
    "SyncRoomMessage",
    "MessageBoard",
    "MessageLike",
    "ResourceRequest",
    "WishlistReply",
    "Base",
]
